name: Coffee Sales Pipeline - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Pytest (Python 3.10 + uv)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          cd coffee_sales_pipeline
          uv sync
          uv pip install -e .

      - name: Run tests
        run: |
          cd coffee_sales_pipeline
          source .venv/bin/activate
          cd ..
          uv run python -m pytest -v --maxfail=1 --disable-warnings
